"""Proposal writer — emits ``promotion-proposal.md`` for human review.

MVP scaffold. The infra-utility AI judgement is deferred to the model runtime
that invokes ``/speckit.aibdd.bdd-analyze``; this module only emits the
scaffold with candidate stats and empty Signed-off section.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .scanner import ScanResult


PROPOSAL_TEMPLATE = """---
generated_at: "{timestamp}"
threshold: {threshold}
total_entries_seen: {total}
status: "pending-review"
---

# DSL Promotion Proposal

> Generated by `/speckit.aibdd.bdd-analyze` Step 6 DSL Promotion Gate
> (`promote-dsl propose`). **Human review required** — run
> `/speckit.aibdd.promote-dsl --proposal <this-file>` once the `Signed-off`
> section below is filled in.

## Candidates

{candidate_table}

## Proposed shared dsl.md additions (preview)

<!--
Populate the 4-layer mapping YAML for each candidate here. Use the schema from
`.claude/skills/aibdd-plan/references/dsl-output-contract.md`（plan `dsl.yml` entry / L1-L4 schema）。
-->

## Proposed step def migrations

<!--
Per `${BDD_CONSTITUTION_PATH}`, list (old-path → new-path) for every
step definition that must move alongside the promoted DSL entry.
-->

## Reviewer Decisions

<!--
For each candidate, choose one of: apply / skip / rename / merge.
Default = apply.
-->

## Signed-off

Reviewer: _<name>_
Date: _<ISO-8601>_
Decision: _<pending | apply | reject>_
"""


def _candidate_table(result: ScanResult) -> str:
    if not result.candidates:
        return "_No candidates._"
    rows = ["| entry_id | occurrences | packages |", "|---|---|---|"]
    for c in result.candidates:
        rows.append(f"| `{c.entry_id}` | {c.occurrences} | {', '.join(c.packages)} |")
    return "\n".join(rows)


def write_proposal(result: ScanResult, target: Path) -> None:
    """Write the promotion-proposal.md file to ``target``."""
    timestamp = datetime.now(tz=timezone.utc).isoformat()
    content = PROPOSAL_TEMPLATE.format(
        timestamp=timestamp,
        threshold=result.threshold,
        total=result.total_entries_seen,
        candidate_table=_candidate_table(result),
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
